package cmd

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/firecrown-media/stax/pkg/config"
	"github.com/firecrown-media/stax/pkg/ddev"
	"github.com/firecrown-media/stax/pkg/ui"
)

// generateDDEVConfig creates DDEV configuration for the project
func generateDDEVConfig(projectDir string, cfg *config.Config) error {
	ui.Section("Generating DDEV Configuration")

	// Check if config already exists
	if ddev.IsConfigured(projectDir) {
		ui.Info("DDEV configuration already exists, skipping generation")
		return nil
	}

	// Prepare DDEV config options
	options := ddev.ConfigOptions{
		ProjectName:        cfg.Project.Name,
		Type:               mapProjectTypeToDDEV(cfg.Project.Type),
		DocRoot:            ".",
		PHPVersion:         cfg.DDEV.PHPVersion,
		DatabaseType:       cfg.DDEV.MySQLType,
		DatabaseVersion:    cfg.DDEV.MySQLVersion,
		RouterHTTPPort:     cfg.DDEV.RouterHTTPPort,
		RouterHTTPSPort:    cfg.DDEV.RouterHTTPSPort,
		XdebugEnabled:      cfg.DDEV.XdebugEnabled,
		UseDNSWhenPossible: cfg.DDEV.UseDNSWhenPossible,
		MutagenEnabled:     cfg.DDEV.MutagenEnabled,
		ComposerVersion:    cfg.DDEV.ComposerVersion,
		NodeJSVersion:      cfg.DDEV.NodeJSVersion,
	}

	// Add additional hostnames for multisite
	if isMultisite(cfg.Project.Type) {
		options.AdditionalHostnames = generateMultisiteHostnames(cfg)
	}

	// Generate config
	ddevConfig, err := ddev.GenerateConfig(projectDir, options)
	if err != nil {
		return fmt.Errorf("failed to generate DDEV config: %w", err)
	}

	// Write config
	if err := ddev.WriteConfig(projectDir, ddevConfig); err != nil {
		return fmt.Errorf("failed to write DDEV config: %w", err)
	}

	ui.Success("Generated DDEV configuration")
	return nil
}

// generateMultisiteNginxConfig creates nginx configuration for multisite
func generateMultisiteNginxConfig(projectDir string, cfg *config.Config) error {
	ui.Section("Generating Multisite Configuration")

	// Create nginx configuration directory
	nginxDir := filepath.Join(projectDir, ".ddev", "nginx_full")
	if err := os.MkdirAll(nginxDir, 0755); err != nil {
		return fmt.Errorf("failed to create nginx directory: %w", err)
	}

	// Generate multisite nginx config based on mode
	var nginxConfig string
	if cfg.Project.Mode == "subdomain" {
		nginxConfig = generateSubdomainNginxConfig(cfg)
	} else {
		nginxConfig = generateSubdirectoryNginxConfig(cfg)
	}

	// Write config
	configPath := filepath.Join(nginxDir, "multisite.conf")
	if err := os.WriteFile(configPath, []byte(nginxConfig), 0644); err != nil {
		return fmt.Errorf("failed to write nginx config: %w", err)
	}

	ui.Success("Generated multisite nginx configuration")
	return nil
}

// generateSubdomainNginxConfig creates nginx config for subdomain multisite
func generateSubdomainNginxConfig(cfg *config.Config) string {
	return fmt.Sprintf(`# WordPress Multisite (subdomain) configuration
# Generated by Stax

# Handle wildcard subdomains for multisite
server_name_in_redirect off;

# Multisite subdomain rewrite rules
if (!-e $request_filename) {
    rewrite /wp-admin$ $scheme://$host$uri/ permanent;
    rewrite ^(/[^/]+)?(/wp-.*) $2 last;
    rewrite ^(/[^/]+)?(/.*\.php) $2 last;
}

# Additional multisite configuration
location / {
    try_files $uri $uri/ /index.php?$args;
}

# Domain: %s
`, cfg.Network.Domain)
}

// generateSubdirectoryNginxConfig creates nginx config for subdirectory multisite
func generateSubdirectoryNginxConfig(cfg *config.Config) string {
	return fmt.Sprintf(`# WordPress Multisite (subdirectory) configuration
# Generated by Stax

# Multisite subdirectory rewrite rules
if (!-e $request_filename) {
    rewrite /wp-admin$ $scheme://$host$uri/ permanent;
    rewrite ^(/[^/]+)?(/wp-.*) $2 last;
    rewrite ^(/[^/]+)?(/.*\.php) $2 last;
}

# Additional multisite configuration
location / {
    try_files $uri $uri/ /index.php?$args;
}

# Domain: %s
`, cfg.Network.Domain)
}

// mapProjectTypeToDDEV converts Stax project type to DDEV type
func mapProjectTypeToDDEV(projectType string) string {
	switch {
	case strings.Contains(projectType, "multisite"):
		return "wordpress"
	default:
		return projectType
	}
}

// mapDDEVTypeToStax converts DDEV project type to Stax type
func mapDDEVTypeToStax(ddevType string) string {
	// DDEV doesn't distinguish multisite, so default to single
	return "wordpress"
}

// generateMultisiteHostnames generates additional hostnames for multisite
func generateMultisiteHostnames(cfg *config.Config) []string {
	// For subdomain multisite, generate wildcard hostname
	if cfg.Project.Mode == "subdomain" {
		return []string{
			fmt.Sprintf("*.%s.ddev.site", cfg.Project.Name),
		}
	}
	return []string{}
}

// isMultisite checks if the project type is a multisite installation
func isMultisite(projectType string) bool {
	return strings.Contains(projectType, "multisite")
}
