package ddev

import (
	"fmt"
	"os"
	"path/filepath"
	"runtime"

	"gopkg.in/yaml.v3"
)

// GenerateConfig creates a DDEV configuration from the provided options
func GenerateConfig(projectPath string, options ConfigOptions) (*DDEVConfig, error) {
	// Apply defaults
	if options.Type == "" {
		options.Type = "wordpress"
	}
	if options.DocRoot == "" {
		options.DocRoot = "."
	}
	if options.PHPVersion == "" {
		options.PHPVersion = "8.1"
	}
	if options.DatabaseType == "" {
		options.DatabaseType = "mysql"
	}
	if options.DatabaseVersion == "" {
		options.DatabaseVersion = "8.0"
	}
	if options.RouterHTTPPort == "" {
		options.RouterHTTPPort = "80"
	}
	if options.RouterHTTPSPort == "" {
		options.RouterHTTPSPort = "443"
	}
	if options.ComposerVersion == "" {
		options.ComposerVersion = "2"
	}
	if options.NodeJSVersion == "" {
		options.NodeJSVersion = "20"
	}

	// Enable Mutagen on macOS by default for performance
	if runtime.GOOS == "darwin" && !options.MutagenEnabled {
		options.MutagenEnabled = true
		if options.PerformanceMode == "" {
			options.PerformanceMode = "mutagen"
		}
	}

	// Add extra packages for PHP YAML support
	if options.WebImageExtraPackages == nil {
		options.WebImageExtraPackages = []string{
			fmt.Sprintf("php%s-yaml", options.PHPVersion),
		}
	}

	// Build configuration
	config := &DDEVConfig{
		Name:                  options.ProjectName,
		Type:                  options.Type,
		DocRoot:               options.DocRoot,
		PHPVersion:            options.PHPVersion,
		WebImageExtraPackages: options.WebImageExtraPackages,
		Database: DatabaseConfig{
			Type:    options.DatabaseType,
			Version: options.DatabaseVersion,
		},
		AdditionalHostnames: options.AdditionalHostnames,
		AdditionalFQDNs:     options.AdditionalFQDNs,
		RouterHTTPPort:      options.RouterHTTPPort,
		RouterHTTPSPort:     options.RouterHTTPSPort,
		XdebugEnabled:       options.XdebugEnabled,
		UseDNSWhenPossible:  options.UseDNSWhenPossible,
		ComposerVersion:     options.ComposerVersion,
		WebEnvironment:      options.WebEnvironment,
		NodeJSVersion:       options.NodeJSVersion,
		MutagenEnabled:      options.MutagenEnabled,
		PerformanceMode:     options.PerformanceMode,
	}

	// Build hooks
	if len(options.PostStartHooks) > 0 || len(options.PostImportHooks) > 0 {
		config.Hooks = &DDEVHooks{}

		// Add default post-start hooks
		defaultPostStart := []HookCommand{
			{Exec: "wp core verify-checksums || true"},
		}

		// Add custom post-start hooks
		for _, hook := range options.PostStartHooks {
			defaultPostStart = append(defaultPostStart, HookCommand{Exec: hook})
		}
		config.Hooks.PostStart = defaultPostStart

		// Add post-import hooks
		if len(options.PostImportHooks) > 0 {
			config.Hooks.PostImport = make([]HookCommand, len(options.PostImportHooks))
			for i, hook := range options.PostImportHooks {
				config.Hooks.PostImport[i] = HookCommand{Exec: hook}
			}
		}
	}

	return config, nil
}

// WriteConfig writes a DDEV configuration to the project directory
func WriteConfig(projectPath string, config *DDEVConfig) error {
	ddevDir := filepath.Join(projectPath, ".ddev")

	// Create .ddev directory if it doesn't exist
	if err := os.MkdirAll(ddevDir, 0755); err != nil {
		return fmt.Errorf("failed to create .ddev directory: %w", err)
	}

	// Write config.yaml
	configPath := filepath.Join(ddevDir, "config.yaml")
	data, err := yaml.Marshal(config)
	if err != nil {
		return fmt.Errorf("failed to marshal config: %w", err)
	}

	// Add header comment
	header := []byte("# DDEV configuration generated by Stax\n# See https://ddev.readthedocs.io/en/stable/users/configuration/config/\n\n")
	data = append(header, data...)

	if err := os.WriteFile(configPath, data, 0644); err != nil {
		return fmt.Errorf("failed to write config file: %w", err)
	}

	return nil
}

// ReadConfig reads the DDEV configuration from a project directory
func ReadConfig(projectPath string) (*DDEVConfig, error) {
	configPath := filepath.Join(projectPath, ".ddev", "config.yaml")

	data, err := os.ReadFile(configPath)
	if err != nil {
		return nil, fmt.Errorf("failed to read config file: %w", err)
	}

	var config DDEVConfig
	if err := yaml.Unmarshal(data, &config); err != nil {
		return nil, fmt.Errorf("failed to parse config: %w", err)
	}

	return &config, nil
}

// UpdateConfig updates specific fields in the DDEV configuration
func UpdateConfig(projectPath string, updates map[string]interface{}) error {
	config, err := ReadConfig(projectPath)
	if err != nil {
		return err
	}

	// Apply updates (this is a simple approach; could use reflection for more complex updates)
	for key, value := range updates {
		switch key {
		case "php_version":
			if v, ok := value.(string); ok {
				config.PHPVersion = v
			}
		case "database.version":
			if v, ok := value.(string); ok {
				config.Database.Version = v
			}
		case "xdebug_enabled":
			if v, ok := value.(bool); ok {
				config.XdebugEnabled = v
			}
		case "additional_hostnames":
			if v, ok := value.([]string); ok {
				config.AdditionalHostnames = v
			}
		case "mutagen_enabled":
			if v, ok := value.(bool); ok {
				config.MutagenEnabled = v
			}
		default:
			return fmt.Errorf("unknown config key: %s", key)
		}
	}

	return WriteConfig(projectPath, config)
}

// ConfigExists checks if a DDEV configuration exists for the project
func ConfigExists(projectPath string) bool {
	configPath := filepath.Join(projectPath, ".ddev", "config.yaml")
	_, err := os.Stat(configPath)
	return err == nil
}

// ValidateConfig validates a DDEV configuration
func ValidateConfig(config *DDEVConfig) error {
	if config.Name == "" {
		return fmt.Errorf("project name is required")
	}
	if config.Type == "" {
		return fmt.Errorf("project type is required")
	}
	if config.PHPVersion == "" {
		return fmt.Errorf("PHP version is required")
	}
	if config.Database.Type == "" {
		return fmt.Errorf("database type is required")
	}
	if config.Database.Version == "" {
		return fmt.Errorf("database version is required")
	}

	// Validate PHP version format (should be like "8.1", "8.2", etc.)
	// This is a simple check; DDEV will do more thorough validation
	if len(config.PHPVersion) < 3 {
		return fmt.Errorf("invalid PHP version format: %s", config.PHPVersion)
	}

	return nil
}

// GetDefaultConfigOptions returns default configuration options
func GetDefaultConfigOptions(projectName string) ConfigOptions {
	return ConfigOptions{
		ProjectName:        projectName,
		DocRoot:            ".",
		Type:               "wordpress",
		PHPVersion:         "8.1",
		DatabaseType:       "mysql",
		DatabaseVersion:    "8.0",
		RouterHTTPPort:     "80",
		RouterHTTPSPort:    "443",
		ComposerVersion:    "2",
		NodeJSVersion:      "20",
		XdebugEnabled:      false,
		UseDNSWhenPossible: true,
		MutagenEnabled:     runtime.GOOS == "darwin",
		PerformanceMode:    "mutagen",
	}
}
