package ddev

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

// nginxMediaProxyTemplate contains server-level directives for media proxying
// These must be included INSIDE a server block, not at HTTP level
const nginxMediaProxyTemplate = `# Remote media proxy configuration
# This allows loading media from {{.CDNName}} without local storage
# Generated by Stax
#
# WARNING: This file contains location blocks that MUST be included inside a server block.
# If DDEV includes nginx_full/*.conf at HTTP level, this will cause errors.
# In that case, use the server block template instead.

location ~ ^/wp-content/uploads/(.*)$ {
    # Try local file first
    try_files $uri @proxy_media;
}

location @proxy_media {
    # Try primary CDN first
    proxy_pass {{.CDNURL}}$request_uri;
    proxy_intercept_errors on;
    proxy_ssl_server_name on;
    proxy_ssl_verify off;

    # Fallback to WPEngine if CDN fails
    error_page 404 = @wpengine_fallback;

    {{if .CacheEnabled}}
    # Caching configuration (requires proxy_cache_path defined at HTTP level)
    proxy_cache media_cache;
    proxy_cache_valid 200 {{.CacheTTL}};
    proxy_cache_valid 404 1m;
    proxy_cache_key "$scheme$request_method$host$request_uri";

    # Cache headers
    expires {{.CacheTTL}};
    add_header Cache-Control "public, immutable";
    add_header X-Cache-Status $upstream_cache_status;
    {{end}}
    add_header X-Proxy-Source "cdn";

    # Proxy headers
    {{range $key, $value := .ProxyHeaders}}
    proxy_set_header {{$key}} {{$value}};
    {{end}}

    # Hide upstream headers
    proxy_hide_header Set-Cookie;
    proxy_ignore_headers Set-Cookie;
}

location @wpengine_fallback {
    proxy_pass {{.WPEngineURL}}$request_uri;
    proxy_ssl_server_name on;
    proxy_ssl_verify off;

    {{if .CacheEnabled}}
    # Caching
    proxy_cache media_cache;
    proxy_cache_valid 200 {{.CacheTTL}};
    proxy_cache_key "$scheme$request_method$host$request_uri";
    expires {{.CacheTTL}};
    {{end}}
    add_header X-Proxy-Source "wpengine";

    # Proxy headers
    {{if .WPEngineHost}}
    proxy_set_header Host {{.WPEngineHost}};
    {{end}}
    proxy_hide_header Set-Cookie;
    proxy_ignore_headers Set-Cookie;
}
`

// nginxMediaProxyServerTemplate wraps location blocks in a complete server block
// This is needed when DDEV includes nginx_full/*.conf files at HTTP context level
const nginxMediaProxyServerTemplate = `# Remote media proxy server block
# Generated by Stax
#
# This complete server block handles media proxy requests.
# It listens on the same ports as the main DDEV server and uses server_name matching.

{{if .CacheEnabled}}
# Cache path configuration (HTTP-level directive)
proxy_cache_path /var/cache/nginx/media
    levels=1:2
    keys_zone=media_cache:10m
    max_size={{.CacheMaxSize}}
    inactive={{.CacheTTL}}
    use_temp_path=off;
{{end}}

# Server block for media proxy
# This supplements the main DDEV server block
server {
    listen 80;
    listen 443 ssl;

    # Match all hostnames (use default_server or specific server_name if needed)
    server_name _;

    # SSL certificate (uses DDEV's certificates)
    ssl_certificate /etc/ssl/certs/master.crt;
    ssl_certificate_key /etc/ssl/certs/master.key;

    # Root and index (match DDEV defaults)
    root /var/www/html;
    index index.php index.html index.htm;

    # Media proxy location blocks
    location ~ ^/wp-content/uploads/(.*)$ {
        # Try local file first
        try_files $uri @proxy_media;
    }

    location @proxy_media {
        # Try primary CDN first
        proxy_pass {{.CDNURL}}$request_uri;
        proxy_intercept_errors on;
        proxy_ssl_server_name on;
        proxy_ssl_verify off;

        # Fallback to WPEngine if CDN fails
        error_page 404 = @wpengine_fallback;

        {{if .CacheEnabled}}
        # Caching configuration
        proxy_cache media_cache;
        proxy_cache_valid 200 {{.CacheTTL}};
        proxy_cache_valid 404 1m;
        proxy_cache_key "$scheme$request_method$host$request_uri";

        # Cache headers
        expires {{.CacheTTL}};
        add_header Cache-Control "public, immutable";
        add_header X-Cache-Status $upstream_cache_status;
        {{end}}
        add_header X-Proxy-Source "cdn";

        # Proxy headers
        {{range $key, $value := .ProxyHeaders}}
        proxy_set_header {{$key}} {{$value}};
        {{end}}

        # Hide upstream headers
        proxy_hide_header Set-Cookie;
        proxy_ignore_headers Set-Cookie;
    }

    location @wpengine_fallback {
        proxy_pass {{.WPEngineURL}}$request_uri;
        proxy_ssl_server_name on;
        proxy_ssl_verify off;

        {{if .CacheEnabled}}
        # Caching
        proxy_cache media_cache;
        proxy_cache_valid 200 {{.CacheTTL}};
        proxy_cache_key "$scheme$request_method$host$request_uri";
        expires {{.CacheTTL}};
        {{end}}
        add_header X-Proxy-Source "wpengine";

        # Proxy headers
        {{if .WPEngineHost}}
        proxy_set_header Host {{.WPEngineHost}};
        {{end}}
        proxy_hide_header Set-Cookie;
        proxy_ignore_headers Set-Cookie;
    }

    # Pass all other requests to PHP-FPM (standard DDEV config)
    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    location ~ \.php$ {
        fastcgi_pass unix:/run/php-fpm.sock;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }
}
`

// GenerateMediaProxyConfig creates Nginx configuration for remote media proxying
func GenerateMediaProxyConfig(projectPath string, options MediaProxyOptions) error {
	if !options.Enabled {
		return nil
	}

	// Set defaults
	if options.CacheTTL == "" {
		options.CacheTTL = "30d"
	}
	if options.CacheMaxSize == "" {
		options.CacheMaxSize = "10g"
	}
	if options.CDNName == "" {
		options.CDNName = "CDN"
	}

	// Default proxy headers
	if options.ProxyHeaders == nil {
		options.ProxyHeaders = map[string]string{
			"X-Real-IP":       "$remote_addr",
			"X-Forwarded-For": "$proxy_add_x_forwarded_for",
		}
	}

	// Create .ddev/nginx_full directory
	nginxDir := filepath.Join(projectPath, ".ddev", "nginx_full")
	if err := os.MkdirAll(nginxDir, 0755); err != nil {
		return fmt.Errorf("failed to create nginx_full directory: %w", err)
	}

	// Use the server block template that wraps location blocks properly
	// This prevents "location directive not allowed here" errors when DDEV includes
	// nginx_full/*.conf files at HTTP context level instead of server context
	tmpl, err := template.New("media-proxy").Parse(nginxMediaProxyServerTemplate)
	if err != nil {
		return fmt.Errorf("failed to parse template: %w", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, options); err != nil {
		return fmt.Errorf("failed to execute template: %w", err)
	}

	// Validate configuration structure before writing
	configContent := buf.String()
	if err := ValidateNginxMediaProxyConfig(configContent); err != nil {
		return fmt.Errorf("generated nginx config is invalid: %w", err)
	}

	// Write to file - this now contains a complete server block
	configPath := filepath.Join(nginxDir, "media-proxy.conf")
	if err := os.WriteFile(configPath, buf.Bytes(), 0644); err != nil {
		return fmt.Errorf("failed to write nginx config: %w", err)
	}

	// Create cache directory setup hook if caching is enabled
	if options.CacheEnabled {
		if err := createCacheDirectory(nginxDir); err != nil {
			return err
		}
	}

	return nil
}

// createCacheDirectory creates a script to set up the nginx cache directory
func createCacheDirectory(nginxDir string) error {
	script := `#!/bin/bash
# Setup script for nginx media cache directory
# Run this inside the DDEV container: ddev exec .ddev/nginx_full/setup-media-cache.sh

mkdir -p /var/cache/nginx/media
chown -R www-data:www-data /var/cache/nginx/media
chmod -R 755 /var/cache/nginx/media
echo "Media cache directory created successfully"
`

	scriptPath := filepath.Join(nginxDir, "setup-media-cache.sh")
	return os.WriteFile(scriptPath, []byte(script), 0755)
}

// ValidateNginxMediaProxyConfig validates that the generated config has proper structure
// to prevent "location directive not allowed here" errors
func ValidateNginxMediaProxyConfig(config string) error {
	// Check that config doesn't start with bare location blocks
	// (which would fail if included at HTTP level)
	trimmed := strings.TrimSpace(config)

	// If config starts with a comment or proxy_cache_path, check for server block
	if strings.HasPrefix(trimmed, "#") || strings.HasPrefix(trimmed, "proxy_cache_path") {
		// These are OK if there's a server block somewhere
		if !strings.Contains(config, "server {") {
			return fmt.Errorf("nginx config must contain a 'server {' block to wrap location directives")
		}
	}

	// If config starts with "location", it's invalid for HTTP-level includes
	if strings.HasPrefix(trimmed, "location") {
		return fmt.Errorf("nginx config starts with 'location' directive - must be wrapped in 'server {' block for DDEV nginx_full includes")
	}

	// Check that location blocks are inside server block
	lines := strings.Split(config, "\n")
	inServerBlock := false
	depth := 0

	for _, line := range lines {
		trimLine := strings.TrimSpace(line)

		// Skip empty lines and comments
		if trimLine == "" || strings.HasPrefix(trimLine, "#") {
			continue
		}

		// Check if line starts with "location " BEFORE updating depth
		// This catches location blocks that are outside server blocks
		if strings.HasPrefix(trimLine, "location ") && !inServerBlock {
			return fmt.Errorf("found location directive outside server block - this will cause nginx errors")
		}

		// Track server block entry
		if strings.Contains(trimLine, "server {") {
			inServerBlock = true
			depth = 1 // We're now 1 level deep in server block
		} else if inServerBlock {
			// Count opening braces (excluding those in strings)
			for _, ch := range trimLine {
				if ch == '{' {
					depth++
				} else if ch == '}' {
					depth--
					if depth == 0 {
						inServerBlock = false
						break
					}
				}
			}
		}
	}

	return nil
}

// WriteNginxConfig writes a custom Nginx configuration to the DDEV project
func WriteNginxConfig(projectPath, filename, content string) error {
	nginxDir := filepath.Join(projectPath, ".ddev", "nginx_full")
	if err := os.MkdirAll(nginxDir, 0755); err != nil {
		return fmt.Errorf("failed to create nginx_full directory: %w", err)
	}

	configPath := filepath.Join(nginxDir, filename)
	if err := os.WriteFile(configPath, []byte(content), 0644); err != nil {
		return fmt.Errorf("failed to write nginx config: %w", err)
	}

	return nil
}

// ReadNginxConfig reads a Nginx configuration file from the DDEV project
func ReadNginxConfig(projectPath, filename string) (string, error) {
	configPath := filepath.Join(projectPath, ".ddev", "nginx_full", filename)
	data, err := os.ReadFile(configPath)
	if err != nil {
		return "", fmt.Errorf("failed to read nginx config: %w", err)
	}
	return string(data), nil
}

// ValidateNginxConfig validates Nginx configuration syntax using DDEV
func ValidateNginxConfig(projectPath string) error {
	mgr := NewManager(projectPath)

	// Execute nginx -t in the container
	err := mgr.Exec([]string{"nginx", "-t"}, &ExecOptions{
		Service: "web",
	})

	if err != nil {
		return fmt.Errorf("nginx configuration is invalid: %w", err)
	}

	return nil
}

// GetDefaultMediaProxyOptions returns default media proxy options
func GetDefaultMediaProxyOptions() MediaProxyOptions {
	return MediaProxyOptions{
		Enabled:      true,
		CDNName:      "BunnyCDN",
		CacheTTL:     "30d",
		CacheMaxSize: "10g",
		CacheEnabled: true,
		ProxyHeaders: map[string]string{
			"X-Real-IP":       "$remote_addr",
			"X-Forwarded-For": "$proxy_add_x_forwarded_for",
		},
	}
}
